/**
 * POST /api/admin/fn/[name] - the Next.js stand-in for DepthMe's `admin-*`
 * Supabase edge functions. Generated by port-admin-console.
 *
 * The session is verified with auth.getUser() (a round trip to Supabase Auth),
 * never by decoding the JWT locally. Only then does a handler get the
 * service-role client. Unknown names answer 404 so an unported screen shows its
 * empty state rather than crashing.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { createClient } from '@supabase/supabase-js';
import { createServerClient } from '@supabase/ssr';
import { isSuperAdmin } from '@/lib/super-admin';
import { ADMIN_FNS } from '@/lib/admin-fns';

const service = () =>
  createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { persistSession: false },
  });

async function verifiedUser(req: NextApiRequest) {
  const bearer = req.headers.authorization?.replace(/^Bearer\s+/i, '').trim();
  if (bearer) {
    const { data } = await service().auth.getUser(bearer);
    if (data.user) return data.user;
  }
  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
    cookies: {
      getAll: () => Object.entries(req.cookies).map(([name, value]) => ({ name, value: value ?? '' })),
      setAll: () => {},
    },
  });
  const { data } = await supabase.auth.getUser();
  return data.user ?? null;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const user = await verifiedUser(req);
  if (!user || !(isSuperAdmin(user))) return res.status(403).json({ error: 'Forbidden' });

  const name = String(req.query.name ?? '');
  const fn = ADMIN_FNS[name];
  if (!fn) return res.status(404).json({ error: `No admin handler for ${name}` });

  try {
    const out = await fn(req.body ?? {}, { user, db: service() });
    return res.status(200).json(out ?? {});
  } catch (e) {
    console.error(`[admin-fn ${name}]`, e);
    return res.status(500).json({ error: e instanceof Error ? e.message : 'Internal error' });
  }
}
