import type { NextApiRequest, NextApiResponse } from 'next';
import { createServiceClient } from '@/lib/supabase/api';
import { isMissingSchema } from '@/lib/billing/service';

/**
 * GET  /api/email/unsubscribe?token=...   — the link in the email footer
 * POST /api/email/unsubscribe?token=...   — RFC 8058 one-click, from the mail
 *                                           client's own "unsubscribe" button
 *
 * CHECKLIST section 9: the published privacy policy already tells users they
 * can unsubscribe through a link, and until now neither the link nor the store
 * existed. That is a live compliance exposure the moment a usage digest ships,
 * which is why this route is part of the same parcel as the first mailer.
 *
 * TOKEN DESIGN. The token is 32 random bytes of hex, generated by Postgres
 * (`encode(gen_random_bytes(32),'hex')` as the column default in migration 034)
 * and stored on the email_preferences row:
 *
 *   - It is NOT derived from the address, so the URL carries no personal data —
 *     no email in a query string that ends up in a proxy log or a referrer.
 *   - It is not guessable, and `anon` has no grant on the table, so a token
 *     cannot be enumerated.
 *   - It is revocable: rotating one row invalidates every old link for that
 *     recipient. An HMAC of the address would be shorter to write and
 *     impossible to revoke.
 *   - It does not expire. An unsubscribe link in a two-year-old email must
 *     still work; that is the whole point of it.
 *
 * Unauthenticated by necessity — the recipient clicks from a mail client — so
 * the token IS the authorisation and the handler runs under the service role.
 * It only ever flips one boolean on one row, and it is idempotent: clicking
 * twice is the same as clicking once.
 *
 * This route governs NON-TRANSACTIONAL mail only. Transactional messages — an
 * invitation, a role change, "your trial has stopped processing" — are not
 * subject to it and lib/email/send.ts does not consult preferences for them.
 */
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET' && req.method !== 'POST') {
    res.setHeader('Allow', 'GET, POST');
    return res.status(405).json({ error: 'method_not_allowed' });
  }

  const raw = req.query.token;
  const token = (Array.isArray(raw) ? raw[0] : raw || '').trim();
  // Shape-check before touching the database: the column default is 64 hex
  // characters, and anything else is a crawler or a mangled link.
  if (!/^[0-9a-f]{32,128}$/i.test(token)) {
    return respond(req, res, 400, 'That unsubscribe link is not valid.');
  }

  const svc = createServiceClient();
  const now = new Date().toISOString();

  const { data, error } = await svc
    .from('email_preferences')
    .update({ unsubscribed_at: now, updated_at: now, source: 'unsubscribe_link' })
    .eq('token', token)
    .select('email, unsubscribed_at')
    .maybeSingle();

  if (error) {
    if (isMissingSchema(error)) {
      console.error('[unsubscribe] email_preferences absent — apply migration 034');
      return respond(
        req,
        res,
        503,
        'We could not record that just now. Please email support@kyriq.com and we will do it by hand.'
      );
    }
    console.error('[unsubscribe] update failed:', error.message);
    return respond(req, res, 500, 'Something went wrong. Please email support@kyriq.com.');
  }

  if (!data) {
    // Either an unknown token or a rotated one. Same answer either way: do not
    // confirm or deny that an address is on file.
    return respond(req, res, 404, 'That unsubscribe link is no longer valid.');
  }

  return respond(
    req,
    res,
    200,
    'You will no longer receive usage and trial updates from Kyriq. ' +
      'Messages about your account that we have to send — invitations, access changes, ' +
      'and notices that processing has stopped — will still reach you.'
  );
}

/**
 * A mail client's one-click POST wants a short machine answer; a human who
 * clicked the link wants a page. Both outcomes are identical server-side.
 */
function respond(req: NextApiRequest, res: NextApiResponse, status: number, message: string) {
  if (req.method === 'POST') {
    return res.status(status).json({ ok: status === 200, message });
  }
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  // No external assets and no scripts: this renders inside whatever browser a
  // mail client opens, including ones with no network beyond the click.
  return res.status(status).send(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${status === 200 ? 'Unsubscribed' : 'Unsubscribe'} &middot; Kyriq</title></head>
<body style="margin:0;padding:48px 24px;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#17212e;">
<div style="max-width:520px;margin:0 auto;background:#fff;border-radius:14px;padding:32px;">
<div style="font-size:18px;font-weight:600;padding-bottom:18px;">Kyriq</div>
<h1 style="font-size:20px;font-weight:600;margin:0 0 14px;">${
    status === 200 ? 'You are unsubscribed' : 'We could not do that'
  }</h1>
<p style="font-size:15px;line-height:1.6;margin:0 0 18px;">${escapeHtml(message)}</p>
<p style="font-size:13px;line-height:1.5;color:#5b6775;margin:0;">Questions? Write to <a href="mailto:support@kyriq.com" style="color:#17212e;">support@kyriq.com</a>.</p>
</div></body></html>`);
}

const escapeHtml = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
