'use client';
/**
 * Kyriq's useAuth(), reduced to what the admin console reads. Generated by
 * port-admin-console. `isAdmin` is this app's own check - cosmetic on the
 * client; the API dispatcher re-verifies every call server-side.
 */
import { useEffect, useState, type ReactNode } from 'react';
import type { User } from '@supabase/supabase-js';
import { supabase } from './supabase';
import { isSuperAdmin } from '@/lib/super-admin';

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    supabase.auth.getUser().then(({ data }) => {
      if (!alive) return;
      setUser(data.user ?? null);
      setLoading(false);
    });
    const { data: sub } = supabase.auth.onAuthStateChange((_e, session) => setUser(session?.user ?? null));
    return () => { alive = false; sub.subscription.unsubscribe(); };
  }, []);

  return {
    user,
    loading,
    isAdmin: isSuperAdmin(user),
    signOut: async () => { await supabase.auth.signOut(); window.location.href = '/'; },
  };
}

/** No-op provider so copied code that wraps in <AuthProvider> still compiles. */
export function AuthProvider({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
