'use client';
/**
 * react-router-dom, as much of it as the Kyriq admin uses, on next/navigation.
 * Generated by the port-admin-console skill. Paths are relative to the admin
 * base, exactly as under Kyriq's <BrowserRouter basename="/admin">.
 */
import NextLink from 'next/link';
import {
  useRouter, usePathname, useParams as useNextParams, useSearchParams as useNextSearchParams,
} from 'next/navigation';
import { forwardRef, useEffect, type AnchorHTMLAttributes, type ReactNode } from 'react';

const BASE = '/admin';

/** "/users" -> "/admin/users"; relative, hash and external targets pass through. */
export function toHref(to: string | { pathname?: string; search?: string; hash?: string }): string {
  const s = typeof to === 'string' ? to : `${to.pathname ?? ''}${to.search ?? ''}${to.hash ?? ''}`;
  if (!s.startsWith('/') || s.startsWith(BASE + '/') || s === BASE || s.startsWith('//')) return s;
  return s === '/' ? BASE : BASE + s;
}

function stripBase(path: string): string {
  if (path === BASE) return '/';
  return path.startsWith(BASE + '/') ? path.slice(BASE.length) : path;
}

type LinkProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
  to: string | { pathname?: string; search?: string; hash?: string };
  replace?: boolean;
  state?: unknown;
  children?: ReactNode;
};

export const Link = forwardRef<HTMLAnchorElement, LinkProps>(function Link({ to, replace, state: _state, ...rest }, ref) {
  return <NextLink ref={ref} href={toHref(to)} replace={replace} {...rest} />;
});

type NavLinkProps = Omit<LinkProps, 'className' | 'children' | 'style'> & {
  end?: boolean;
  className?: string | ((s: { isActive: boolean; isPending: boolean }) => string | undefined);
  style?: React.CSSProperties | ((s: { isActive: boolean; isPending: boolean }) => React.CSSProperties | undefined);
  children?: ReactNode | ((s: { isActive: boolean; isPending: boolean }) => ReactNode);
};

export const NavLink = forwardRef<HTMLAnchorElement, NavLinkProps>(function NavLink({ to, end, className, style, children, ...rest }, ref) {
  const path = stripBase(usePathname() ?? '/');
  const target = stripBase(toHref(to).split(/[?#]/)[0]);
  const isActive = end || target === '/' ? path === target : path === target || path.startsWith(target + '/');
  const s = { isActive, isPending: false };
  return (
    <Link
      ref={ref}
      to={to}
      aria-current={isActive ? 'page' : undefined}
      className={typeof className === 'function' ? className(s) : className}
      style={typeof style === 'function' ? style(s) : style}
      {...rest}
    >
      {typeof children === 'function' ? children(s) : children}
    </Link>
  );
});

export function useNavigate() {
  const router = useRouter();
  return (to: string | number, opts?: { replace?: boolean }) => {
    if (typeof to === 'number') return to < 0 ? router.back() : router.forward();
    return opts?.replace ? router.replace(toHref(to)) : router.push(toHref(to));
  };
}

export function useLocation() {
  const pathname = stripBase(usePathname() ?? '/');
  const sp = useNextSearchParams();
  const search = sp && sp.toString() ? `?${sp.toString()}` : '';
  return { pathname, search, hash: typeof window === 'undefined' ? '' : window.location.hash, state: null, key: pathname + search };
}

export function useParams<T extends Record<string, string | undefined> = Record<string, string | undefined>>(): T {
  return (useNextParams() ?? {}) as unknown as T;
}

export function useSearchParams(): [URLSearchParams, (next: URLSearchParams | Record<string, string>) => void] {
  const sp = useNextSearchParams();
  const router = useRouter();
  const pathname = usePathname() ?? BASE;
  const current = new URLSearchParams(sp?.toString() ?? '');
  const set = (next: URLSearchParams | Record<string, string>) => {
    const q = new URLSearchParams(next as Record<string, string>).toString();
    router.replace(q ? `${pathname}?${q}` : pathname);
  };
  return [current, set];
}

export function Navigate({ to, replace }: { to: string; replace?: boolean }) {
  const navigate = useNavigate();
  useEffect(() => { navigate(to, { replace }); }, [to, replace]); // eslint-disable-line react-hooks/exhaustive-deps
  return null;
}
