'use client';
/** DepthMe's `supabase` singleton, backed by this app's browser client. Generated by port-admin-console. */
import { createClient } from '@/lib/supabase/client';

export const supabase = createClient();
