/**
 * Admin handler registry for /api/admin/fn/[name]. Generated by
 * port-admin-console; add one entry per DepthMe edge-function name you port.
 * Each handler runs only after the dispatcher verified a super admin.
 */
import type { SupabaseClient, User } from '@supabase/supabase-js';
import metrics from './admin-metrics';
import health from './admin-health';
import usersList from './admin-users-list';
import userDetail from './admin-user-detail';
import userAction from './admin-user-action';
import setRole from './admin-set-role';
import listAdmins from './admin-list-admins';
import findUserByEmail from './admin-find-user-by-email';
import grantPremium from './admin-grant-premium';
import stripeQuery from './admin-stripe-query';
import platformBreakdown from './admin-platform-breakdown';
import stripeSync from './admin-stripe-sync';
import funnelQuery from './admin-funnel-query';
import { activityByHour, eventsQuery, landingQuery, visitorsQuery } from './analytics-empty';

export type AdminCtx = { user: User; db: SupabaseClient };
export type AdminFn = (body: Record<string, unknown>, ctx: AdminCtx) => Promise<unknown>;

export const ADMIN_FNS: Record<string, AdminFn> = {
  'admin-metrics': metrics,
  'admin-health': health,
  'admin-users-list': usersList,
  'admin-user-detail': userDetail,
  'admin-user-action': userAction,
  'admin-set-role': setRole,
  'admin-list-admins': listAdmins,
  'admin-find-user-by-email': findUserByEmail,
  'admin-grant-premium': grantPremium,
  'admin-stripe-query': stripeQuery,
  'admin-platform-breakdown': platformBreakdown,
  'admin-stripe-sync': stripeSync,
  'admin-events-query': eventsQuery,
  'admin-funnel-query': funnelQuery,
  'admin-landing-query': landingQuery,
  'admin-visitors-query': visitorsQuery,
  'admin-activity-by-hour': activityByHour,
};
